"use strict";const t=require("electron"),p=require("path"),o=require("fs"),F=require("child_process"),A=require("os"),R={logPath:"/tmp/chessray-app.log",overlayWindowOptions:{type:"panel"},configureOverlayWindow(e){e.setAlwaysOnTop(!0,"screen-saver",1),e.setVisibleOnAllWorkspaces(!0,{visibleOnFullScreen:!0})},getFrontmostPid(){return new Promise(e=>{F.execFile("osascript",["-e",'tell application "System Events" to unix id of first process whose frontmost is true'],(n,r)=>{if(n)return e(null);e(r.trim()||null)})})},showInDock(e){var n;(n=e.dock)==null||n.show()},getScreenCaptureStatus(e){return e.getMediaAccessStatus("screen")},quitOnAllWindowsClosed:!1},N={logPath:p.join(A.tmpdir(),"chessray-app.log"),overlayWindowOptions:{},configureOverlayWindow(e){e.setAlwaysOnTop(!0,"screen-saver",1),e.setVisibleOnAllWorkspaces(!0)},getFrontmostPid(){return new Promise(e=>{const n=`
        Add-Type @"
          using System;
          using System.Runtime.InteropServices;
          public class FG {
            [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();
            [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint pid);
          }
"@
        $hwnd = [FG]::GetForegroundWindow()
        $pid = 0
        [void][FG]::GetWindowThreadProcessId($hwnd, [ref]$pid)
        Write-Output $pid
      `.trim();F.execFile("powershell",["-NoProfile","-Command",n],(r,s)=>{if(r)return e(null);e(s.trim()||null)})})},showInDock(e){},getScreenCaptureStatus(){return"granted"},quitOnAllWindowsClosed:!0},O={logPath:p.join(A.tmpdir(),"chessray-app.log"),overlayWindowOptions:{},configureOverlayWindow(e){e.setAlwaysOnTop(!0,"screen-saver",1),e.setVisibleOnAllWorkspaces(!0)},getFrontmostPid(){return new Promise(e=>{F.execFile("xdotool",["getactivewindow","getwindowpid"],(n,r)=>{if(n)return e(null);e(r.trim()||null)})})},showInDock(e){},getScreenCaptureStatus(){return"granted"},quitOnAllWindowsClosed:!0},j={darwin:R,win32:N,linux:O},f=j[process.platform]??O,l=f.logPath;o.writeFileSync(l,`[main] Process started at ${new Date().toISOString()}
`);process.on("uncaughtException",e=>{o.appendFileSync(l,`[main] UNCAUGHT: ${e.stack}
`)});process.on("unhandledRejection",e=>{o.appendFileSync(l,`[main] UNHANDLED REJECTION: ${e}
`)});t.protocol.registerSchemesAsPrivileged([{scheme:"chess-vendor",privileges:{standard:!0,secure:!0,supportFetchAPI:!0,corsEnabled:!0}}]);let i=null,a=null,u=null;const E=t.app.isPackaged?p.join(process.resourcesPath,"vendor"):p.resolve(__dirname,"../../../../vendor");function C(){return p.join(__dirname,"preload.js")}function T(){const e=new t.BrowserWindow({show:!1,width:800,height:600,webPreferences:{preload:C(),nodeIntegration:!1,contextIsolation:!0,sandbox:!1,webSecurity:!1,backgroundThrottling:!1}});return e.loadFile(p.join(__dirname,"../renderer/analysis_window/index.html")),e.webContents.on("console-message",(n,r,s)=>{o.appendFileSync(l,`[analysis-renderer] ${s}
`)}),e.webContents.on("did-fail-load",(n,r,s)=>{o.appendFileSync(l,`[analysis-renderer] LOAD FAILED: ${r} ${s}
`)}),e.webContents.on("render-process-gone",(n,r)=>{o.appendFileSync(l,`[analysis-renderer] CRASHED: ${JSON.stringify(r)}
`)}),e}function P(){if(y!=null){const e=t.screen.getAllDisplays().find(n=>n.id===y);if(e)return e}return t.screen.getPrimaryDisplay()}function q(){const e=P(),{x:n,y:r}=e.bounds,{width:s,height:d}=e.size,c=new t.BrowserWindow({width:s,height:d,x:n,y:r,transparent:!0,frame:!1,hasShadow:!1,resizable:!1,fullscreenable:!1,...f.overlayWindowOptions,webPreferences:{preload:C(),nodeIntegration:!1,contextIsolation:!0}});c.setIgnoreMouseEvents(!0,{forward:!0}),c.setContentProtection(!0),f.configureOverlayWindow(c),c.loadFile(p.join(__dirname,"../renderer/overlay_window/index.html")),c.webContents.on("console-message",(m,S,v)=>{o.appendFileSync(l,`[overlay-renderer] ${v}
`)}),c.webContents.on("did-fail-load",(m,S,v)=>{o.appendFileSync(l,`[overlay-renderer] LOAD FAILED: ${S} ${v}
`)}),c.webContents.on("render-process-gone",(m,S)=>{o.appendFileSync(l,`[overlay-renderer] CRASHED: ${JSON.stringify(S)}
`)});const $=()=>{const m=P();x(m)};return c.webContents.once("did-finish-load",$),c.on("move",$),c.on("resize",$),c.show(),c}let y=null;function _(){return p.join(t.app.getPath("userData"),"chessray-prefs.json")}function z(e){try{const n=_();let r={};try{r=JSON.parse(o.readFileSync(n,"utf8"))}catch{}r.displayId=e,o.writeFileSync(n,JSON.stringify(r))}catch{}}function B(){try{const e=JSON.parse(o.readFileSync(_(),"utf8"));return typeof e.displayId=="number"?e.displayId:null}catch{return null}}async function W(e){const n=await t.desktopCapturer.getSources({types:["screen"],thumbnailSize:{width:1,height:1}});if(n.length===0)throw new Error("No screen source found");if(e!=null){const s=n.find(d=>d.display_id===String(e));if(s)return console.log(`[chessray] Matched display ${e} → source ${s.id} (${s.name})`),s.id;console.log(`[chessray] No source for display ${e}, falling back to first`)}const r=n[0];return console.log(`[chessray] Auto-selected screen source: ${r.id} (${r.name})`),r.id}function L(e){if(!a||a.isDestroyed())return;const{x:n,y:r}=e.bounds,{width:s,height:d}=e.size;a.setBounds({x:n,y:r,width:s,height:d}),o.appendFileSync(l,`[chessray] Overlay moved to display ${e.id}: ${n},${r} ${s}x${d}
`)}function x(e){if(!a||a.isDestroyed())return;const n=a.getBounds(),r={size:e.size,workArea:e.workArea,scaleFactor:e.scaleFactor,overlayBounds:n,displayBounds:e.bounds};o.appendFileSync(l,`[chessray] Display: size=${JSON.stringify(e.size)} workArea=${JSON.stringify(e.workArea)} scale=${e.scaleFactor} overlayBounds=${JSON.stringify(n)} displayBounds=${JSON.stringify(e.bounds)}
`),a.webContents.send("display-info",r)}async function I(e){const n=t.screen.getAllDisplays().find(s=>s.id===e);if(!n)return;y=e,z(e),o.appendFileSync(l,`[chessray] Switching to display ${e}
`),i&&!i.isDestroyed()&&i.webContents.send("stop-capture"),L(n),x(n);const r=await W(e);M(r),D()}function D(){var r;if(process.platform!=="darwin")return;const e=t.screen.getAllDisplays(),n=[];if(e.length>1){for(const s of e){const c=s.id===t.screen.getPrimaryDisplay().id?`Built-in Display (${s.size.width}×${s.size.height})`:`Display (${s.size.width}×${s.size.height})`;n.push({label:c,type:"checkbox",checked:s.id===y,click:()=>I(s.id)})}n.push({type:"separator"})}n.push({label:"Reset Panel Position",click:()=>{a&&!a.isDestroyed()&&a.webContents.send("reset-panel-position")}}),(r=t.app.dock)==null||r.setMenu(t.Menu.buildFromTemplate(n))}function J(){t.session.defaultSession.protocol.handle("chess-vendor",e=>{const n=new URL(e.url),r=p.join(decodeURIComponent(n.hostname),decodeURIComponent(n.pathname)),s=p.join(E,r);return new Response(o.readFileSync(s),{headers:{"Content-Type":G(s)}})})}function G(e){return e.endsWith(".js")||e.endsWith(".mjs")?"application/javascript":e.endsWith(".wasm")?"application/wasm":e.endsWith(".onnx")?"application/octet-stream":e.endsWith(".html")?"text/html":e.endsWith(".css")?"text/css":"application/octet-stream"}let g=null,b=!1,h=null;function M(e){console.log(`[chessray] Starting capture: ${e}`),o.appendFileSync(l,`[chessray] Starting capture: ${e}
`),g=e,b=!1,(!i||i.isDestroyed())&&(i=T()),(!a||a.isDestroyed())&&(a=q()),h&&clearInterval(h),h=setInterval(()=>{if(b){clearInterval(h),h=null;return}o.appendFileSync(l,`[chessray] Retrying start-capture (renderer not ready yet)
`),i&&!i.isDestroyed()&&i.webContents.send("start-capture",g)},2e3)}t.ipcMain.on("renderer-ready",()=>{o.appendFileSync(l,`[chessray] Analysis renderer ready
`),b=!0,g&&i&&!i.isDestroyed()&&i.webContents.send("start-capture",g)});t.ipcMain.handle("get-source-id",()=>g);t.ipcMain.on("frame-result",(e,n)=>{a&&!a.isDestroyed()&&a.webContents.send("frame-result",n)});t.ipcMain.on("debug-log",(e,n)=>{console.log(`[chessray] ${n}`),o.appendFileSync(l,`[chessray] ${n}
`)});t.ipcMain.on("set-mouse-passthrough",(e,n)=>{a&&!a.isDestroyed()&&a.setIgnoreMouseEvents(n,{forward:!0})});t.ipcMain.on("set-always-on-top",(e,n)=>{a&&!a.isDestroyed()&&(n?f.configureOverlayWindow(a):a.setAlwaysOnTop(!1))});t.ipcMain.on("minimize-app",()=>{t.app.hide()});t.ipcMain.on("close-app",()=>{t.app.quit()});t.ipcMain.on("open-external",(e,n)=>{typeof n=="string"&&n.startsWith("https://")&&t.shell.openExternal(n)});t.ipcMain.on("toggle-lichess",(e,n,r)=>{if(u&&!u.isDestroyed()){u.close(),u=null;return}const s=n.replace(/ /g,"_"),d=r==="black"?"black":"white";u=new t.BrowserWindow({width:750,height:700,alwaysOnTop:!0,title:"Lichess Analysis",autoHideMenuBar:!0,webPreferences:{contextIsolation:!0,sandbox:!0}}),u.loadURL(`https://lichess.org/analysis/${s}?color=${d}`),u.on("closed",()=>{u=null})});t.ipcMain.on("update-lichess",(e,n,r)=>{if(!u||u.isDestroyed())return;const s=n.replace(/ /g,"_"),d=r==="black"?"black":"white";u.loadURL(`https://lichess.org/analysis/${s}?color=${d}`)});t.ipcMain.on("set-max-depth",(e,n)=>{i&&!i.isDestroyed()&&i.webContents.send("set-max-depth",n)});t.ipcMain.on("set-multi-pv-max",(e,n)=>{i&&!i.isDestroyed()&&i.webContents.send("set-multi-pv-max",n)});t.ipcMain.on("set-multi-pv-ramp",(e,n)=>{i&&!i.isDestroyed()&&i.webContents.send("set-multi-pv-ramp",n)});t.ipcMain.on("set-change-detect",(e,n)=>{i&&!i.isDestroyed()&&i.webContents.send("set-change-detect",n)});t.ipcMain.on("set-target-fps",(e,n)=>{i&&!i.isDestroyed()&&i.webContents.send("set-target-fps",n)});let w=null;function H(){const e=new Date,n=r=>String(r).padStart(2,"0");return`${e.getFullYear()}-${n(e.getMonth()+1)}-${n(e.getDate())}-${n(e.getHours())}${n(e.getMinutes())}${n(e.getSeconds())}`}function k(e,n){i&&!i.isDestroyed()&&i.webContents.send("recording-state-changed",e,n),a&&!a.isDestroyed()&&a.webContents.send("recording-state-changed",e,n)}t.ipcMain.on("start-recording",()=>{const e=p.join(t.app.getPath("home"),"chessray-recordings",H());o.mkdirSync(e,{recursive:!0}),w=e,o.appendFileSync(l,`[main] Recording started → ${e}
`),k(!0,e)});t.ipcMain.on("stop-recording",()=>{o.appendFileSync(l,`[main] Recording stopped (was ${w})
`),w=null,k(!1,null)});t.ipcMain.on("save-frame-artifact",(e,n,r)=>{if(w)try{o.writeFileSync(p.join(w,n),Buffer.from(r))}catch(s){o.appendFileSync(l,`[main] save-frame-artifact failed: ${s}
`)}});const U=t.app.requestSingleInstanceLock();U||t.app.quit();t.app.whenReady().then(()=>{t.app.setName("ChessRay"),f.showInDock(t.app);const e=B();y=e!=null&&t.screen.getAllDisplays().some(s=>s.id===e)?e:t.screen.getPrimaryDisplay().id,D(),t.screen.on("display-added",()=>D()),t.screen.on("display-removed",()=>{y!=null&&!t.screen.getAllDisplays().some(s=>s.id===y)&&I(t.screen.getPrimaryDisplay().id),D()}),J(),t.session.defaultSession.setDisplayMediaRequestHandler((s,d)=>{d({})});const r=f.getScreenCaptureStatus(t.systemPreferences);o.writeFileSync(l,`[chessray] App ready. Screen status=${r} platform=${process.platform} (trying capture)
`),W(y).then(s=>M(s)).catch(s=>{o.appendFileSync(l,`[chessray] Failed to get screen source: ${s}
`),console.error(`[chessray] Failed to get screen source: ${s}`)})});t.app.on("window-all-closed",()=>{f.quitOnAllWindowsClosed&&t.app.quit()});
