/**
 * Vite plugin: stamps packages/overlay-ui/src/build-info.generated.ts with
 * the current short git SHA + build time before each bundle is produced.
 *
 * Used only by one-shot vite builds (the Electron renderer build invoked
 * via commit.sh's `npm run install-app`, and the extension's production
 * `npm run build` when vite-dev isn't running). Dev-server file refresh
 * is handled by scripts/local/build-info-watcher.sh — keeping this plugin
 * out of any long-running vite-dev process means editing its source
 * doesn't restart vite, which would otherwise kill CRXJS's HMR connection
 * and force a manual chrome://extensions reload.
 *
 * mount-overlay imports the generated module and surfaces the values in
 * the diagnostics view so the running bundle's commit is visible.
 *
 * The generated file is gitignored. tsc only needs a placeholder to
 * typecheck; the plugin overwrites it before each bundle.
 */

import { execSync } from 'node:child_process';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const targetPath = resolve(__dirname, 'src', 'build-info.generated.ts');

function gitShortSha(): string {
  try { return execSync('git rev-parse --short HEAD', { cwd: repoRoot }).toString().trim(); }
  catch { return 'dev'; }
}

function refresh(): void {
  const commit = gitShortSha();
  const time = new Date().toISOString().slice(11, 19); // HH:MM:SS UTC
  const content =
    `// Auto-generated by the build-info vite plugin on every rebuild.\n` +
    `// Do not edit; gitignored.\n` +
    `export const BUILD_COMMIT = ${JSON.stringify(commit)};\n` +
    `export const BUILD_TIME = ${JSON.stringify(time)};\n`;
  // Skip the write when only BUILD_TIME would differ — avoids rewriting
  // the file (and triggering downstream watchers) on every consecutive
  // build that lands on the same commit.
  if (existsSync(targetPath)) {
    const cur = readFileSync(targetPath, 'utf8');
    const cleanCur = cur.replace(/BUILD_TIME = "[^"]*"/, '');
    const cleanNew = content.replace(/BUILD_TIME = "[^"]*"/, '');
    if (cleanCur === cleanNew) return;
  }
  writeFileSync(targetPath, content);
}

export function buildInfoPlugin(): Plugin {
  return {
    name: 'chessray-build-info',
    buildStart() { refresh(); },
  };
}
