/**
 * Vite plugin: writes packages/overlay-ui/src/build-info.generated.ts with
 * the current short git SHA + build time on every build / HMR rebuild.
 *
 * mount-overlay imports the generated module and surfaces the values in
 * the diagnostics view, so the user can see at a glance whether Chrome /
 * Electron is running the latest dist.
 *
 * The file is gitignored. tsc only needs a placeholder to typecheck;
 * the plugin overwrites it before each bundle is produced.
 */

import { execSync } from 'node:child_process';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const targetPath = resolve(__dirname, 'src', 'build-info.generated.ts');

function gitShortSha(): string {
  try { return execSync('git rev-parse --short HEAD', { cwd: repoRoot }).toString().trim(); }
  catch { return 'dev'; }
}

function refresh(): void {
  const commit = gitShortSha();
  const time = new Date().toISOString().slice(11, 19); // HH:MM:SS UTC
  const content =
    `// Auto-generated by the build-info vite plugin on every rebuild.\n` +
    `// Do not edit; gitignored.\n` +
    `export const BUILD_COMMIT = ${JSON.stringify(commit)};\n` +
    `export const BUILD_TIME = ${JSON.stringify(time)};\n`;
  // Skip the write (and the resulting HMR ping) when nothing changed —
  // otherwise every transform-trigger refreshes BUILD_TIME and forces a
  // full reload on every dev-server tick.
  if (existsSync(targetPath)) {
    const cur = readFileSync(targetPath, 'utf8');
    // Compare only the COMMIT line so a steady stream of HMR updates
    // doesn't churn BUILD_TIME and reload the page every second.
    const cleanCur = cur.replace(/BUILD_TIME = "[^"]*"/, '');
    const cleanNew = content.replace(/BUILD_TIME = "[^"]*"/, '');
    if (cleanCur === cleanNew) return;
  }
  writeFileSync(targetPath, content);
}

export function buildInfoPlugin(): Plugin {
  return {
    name: 'chessray-build-info',
    // Production / one-shot build path: write before bundling starts.
    buildStart() { refresh(); },
    // Dev server path: refresh once at boot, then on every file change so
    // post-commit rebuilds (HMR) pick up the new commit hash.
    configureServer(server) {
      refresh();
      server.watcher.on('change', () => refresh());
    },
  };
}
